type Doctor = {
  text: string;
  value: string;
};

export const RAW_DOCTORS = [
  { text: 'Agena, Joanna' },
  { text: 'Alassas, Mohamed' },
  { text: 'Aye, Ralph' },
  { text: 'Barnett, Todd' },
  { text: 'Barr, Darlene' },
  { text: 'Bastawrous, Amir' },
  { text: 'Batchelder, Ami' },
  { text: 'Benkers, Tara' },
  { text: 'Bensinger, William' },
  { text: 'Bhark, Sandy' },
  { text: 'Blanshan, Stephanie' },
  { text: 'Bograd, Adam' },
  { text: 'BonDurant, Amy' },
  { text: 'Brower, Jessica' },
  { text: 'Brown, Thomas' },
  { text: 'Buchanan, Claire' },
  { text: 'Buscariollo, Daniela', value: 'Buscariolo, Daniela' },
  { text: 'Chen, Grace' },
  { text: 'Clay, Martha' },
  { text: 'Cobbs, Charles' },
  { text: 'Dong, David' },
  { text: 'Douglas, Robert' },
  { text: 'Drescher, Charles' },
  { text: 'Eden, Michelle' },
  { text: 'Egan, Dan' },
  { text: 'Ellis, Erin' },
  { text: 'Eulau, Stephen' },
  { text: 'Farivar, Alexander' },
  { text: 'Fer, Mehmet' },
  { text: 'Gilbert, Christopher' },
  { text: 'Gold, Philip' },
  { text: 'Goldberg, Sheldon' },
  { text: 'Golden, Joseph' },
  { text: 'Goldie, Christina (Christa)' },
  { text: 'Gorden, Jed' },
  { text: 'Griffin, John' },
  { text: 'Groves, Kashina' },
  { text: 'Han, Michelle' },
  { text: 'Hawkins, Melinda' },
  { text: 'Hegerova, Livia' },
  { text: 'Hendershott, Karen' },
  { text: 'Henson, John' },
  { text: 'Herbert Aliea' },
  { text: 'Holdread, Heather' },
  { text: 'Johnston, Eileen' },
  { text: 'Kaplan, Henry (Hank)' },
  { text: 'Kim, Namou' },
  { text: 'Kim, Patricia' },
  { text: 'Kratz, Rodney' },
  { text: 'Landis, Daniel' },
  { text: 'Lazarus, Laura' },
  { text: 'Lee, Christine' },
  { text: 'Lee, Douglas' },
  { text: 'Lee, Ellyn' },
  { text: 'Lindsley, Skylar' },
  { text: 'Loiselle, Christopher' },
  { text: 'Lopez, Jay' },
  { text: 'Lott, Jenny' },
  { text: 'Louie, Brian' },
  { text: 'Lynn, Cecilia' },
  { text: 'Marrs, Jessie' },
  { text: 'Mawad, Raya' },
  { text: 'McCormick, Kinsey' },
  { text: 'Mehta, Vivek' },
  { text: 'Meier, Robert' },
  { text: 'Menon, Raman' },
  { text: 'Montgomery, Susan' },
  { text: 'Moore, David' },
  { text: 'Morgan, Amy' },
  { text: 'Morris, Astrid' },
  { text: 'Muggoch, Nancy' },
  { text: 'Musa, Fernanda' },
  { text: 'Ong, Evan' },
  { text: 'Pagel, John' },
  { text: 'Paget, Ellen' },
  { text: 'Palmer, Martin' },
  { text: 'Park, Min' },
  { text: 'Patel, Krish' },
  { text: 'Paulson, Kelly' },
  { text: 'Peters, William' },
  { text: 'Peterson, K.L.' },
  { text: 'Pollock, Darren' },
  { text: 'Press, Joshua' },
  { text: 'Ranker, Elizabeth' },
  { text: 'Rinn, Kristine' },
  { text: 'Robin, Jeffrey' },
  { text: 'Ryu, Lio' },
  { text: 'Shah, Chirag' },
  { text: 'Shango, Maryann' },
  { text: 'Sharma, Nancy' },
  { text: 'Simmons, Forrest' },
  { text: 'Sniezek, Joseph' },
  { text: 'Spiegel, James' },
  { text: 'Subramaniam, Somasundaram (Soma)' },
  { text: 'Takamiya, Robert' },
  { text: 'Gensert, Emma', value: 'Thomas, Emma' },
  { text: 'Tierney, Shannon' },
  { text: 'Tiu, Maitram Christine' },
  { text: 'Vallieres, Eric' },
  { text: 'Vaynshteyn, Rostislav' },
  { text: 'Veljovich, Dan' },
  { text: 'Vermeulen, Sandra' },
  { text: 'Vyas, Shilpa' },
  { text: 'Wahl, Tanya' },
  { text: 'Ward, Jeffery' },
  { text: 'West, Howard (Jack)' },
  { text: 'Wulff, Jennifer' },
  { text: 'Xie, Bin' },
  { text: 'Yan, Fengting' },
  { text: 'Zhao, Song' },
  { text: 'Zucker, David' },
  { text: 'Unassigned' }
];

export const DOCTORS: Doctor[] = RAW_DOCTORS.map(doctor => ({
  ...doctor,
  value: doctor.value || doctor.text
}));
